{{- if (include "kubeflow.tensorboard.controller.enabled" . | eq "true") -}}

apiVersion: v1
kind: Service
metadata:
  {{- with .Values.tensorboard.controller.kubeRbacProxy.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "kubeflow.tensorboard.controller.labels" . | nindent 4 }}
  name: {{ include "kubeflow.tensorboard.controller.kubeRbacProxy.svc.name" . }}
  namespace: {{ include "kubeflow.namespace" . }}
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    {{- include "kubeflow.tensorboard.controller.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: {{ .Values.tensorboard.controller.kubeRbacProxy.service.type }}

{{- end }}
