{{- if (include "kubeflow.trainingOperator.enabled" . | eq "true") -}}

apiVersion: v1
kind: Service
metadata:
  {{- with .Values.trainingOperator.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "kubeflow.trainingOperator.labels" . | nindent 4 }}
  name: {{ include "kubeflow.trainingOperator.svc.name" . }}
  namespace: {{ include "kubeflow.namespace" . }}
spec:
  ports:
    - name: monitoring-port
      port: 8080
      targetPort: 8080
  selector:
    {{- include "kubeflow.trainingOperator.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: {{ .Values.trainingOperator.service.type }}

{{- end }}
